'use client';
import { useEffect, useMemo, useState } from 'react';
import { addEntry, firestoreErrorMessage, listEntries, listJourneys } from '@/lib/data';
import { isoDate, money, parseMoney, sumStats } from '@/lib/format';
import { useAuth } from '@/components/AuthProvider';
import type { Entry, Journey } from '@/types';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, Legend } from 'recharts';

export default function Dashboard(){
 const {user}=useAuth();
 const [entries,setEntries]=useState<Entry[]>([]),[journeys,setJourneys]=useState<Journey[]>([]),[loading,setLoading]=useState(true),[showNew,setShowNew]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false);
 const [type,setType]=useState<'income'|'expense'>('income'),[date,setDate]=useState(isoDate(new Date())),[amount,setAmount]=useState(''),[category,setCategory]=useState('Corridas'),[platform,setPlatform]=useState('Uber'),[description,setDescription]=useState('');

 async function load(){if(!user)return; setLoading(true);setError(''); try{const now=new Date(); const start=new Date(now.getFullYear(),now.getMonth(),1); const [e,j]=await Promise.all([listEntries(user.uid,isoDate(start),isoDate(now)),listJourneys(user.uid,isoDate(start),isoDate(now))]); setEntries(e);setJourneys(j)}catch(cause){setError(firestoreErrorMessage(cause,'Não foi possível carregar seus dados.'))}finally{setLoading(false)}}

 useEffect(()=>{load()},[user]);
 useEffect(()=>{
  if(typeof window === 'undefined') return;
  const params = new URLSearchParams(window.location.search);
  setShowNew(params.get('novo') === '1');
 },[]);

 const stats=useMemo(()=>sumStats(entries),[entries]); const km=journeys.reduce((s,j)=>s+Math.max(0,Number(j.kmEnd)-Number(j.kmStart)),0); const hours=journeys.reduce((s,j)=>{if(!j.startedAt||!j.endedAt)return s; const [h1,m1]=j.startedAt.split(':').map(Number),[h2,m2]=j.endedAt.split(':').map(Number); return s+Math.max(0,(h2*60+m2-h1*60-m1)/60)},0);
 const chart=useMemo(()=>{const map:any={}; entries.forEach(e=>{map[e.date]??={date:e.date.slice(8,10),Faturamento:0,Gastos:0,Lucro:0}; if(e.type==='income')map[e.date].Faturamento+=e.amount;else map[e.date].Gastos+=e.amount;map[e.date].Lucro=map[e.date].Faturamento-map[e.date].Gastos}); return Object.values(map).reverse()},[entries]);
 async function save(){const parsedAmount=parseMoney(amount);if(!user||saving)return;if(!date||!Number.isFinite(parsedAmount)||parsedAmount<=0){setError('Informe uma data e um valor maior que zero.');return;}const entry={date,type,amount:parsedAmount,category:type==='income'?'Corridas':category,platform:type==='income'?platform:'',description:description.trim()};setSaving(true);setError('');const {id,completed}=addEntry(user.uid,entry);const firstDay=isoDate(new Date(new Date().getFullYear(),new Date().getMonth(),1));const today=isoDate(new Date());if(date>=firstDay&&date<=today)setEntries(current=>[{...entry,id},...current].sort((a,b)=>b.date.localeCompare(a.date)));setAmount('');setDescription('');setShowNew(false);setSaving(false);setSyncing(true);void completed.then(()=>setSyncing(false)).catch(cause=>{setEntries(current=>current.filter(item=>item.id!==id));setSyncing(false);setError(firestoreErrorMessage(cause,'Não foi possível confirmar o lançamento no Firestore.'));});}
 return <><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:16,flexWrap:'wrap'}}><div><h1 style={{margin:0}}>Olá, {user?.displayName?.split(' ')[0]||'motorista'} 👋</h1><p className="muted">Resumo do mês atual</p></div><button className="btn btn-primary" onClick={()=>setShowNew(!showNew)}>+ Novo lançamento</button></div>
 {error&&<div className="error" style={{marginTop:16}}>{error}</div>}{syncing&&<p className="muted" style={{marginTop:16}}>Salvando na nuvem...</p>}
 {showNew&&<div className="card" style={{marginTop:18}}><h3 style={{marginTop:0}}>Novo lançamento</h3><div className="tabs"><button className={`tab ${type==='income'?'active':''}`} onClick={()=>setType('income')} disabled={saving}>Receita</button><button className={`tab ${type==='expense'?'active':''}`} onClick={()=>setType('expense')} disabled={saving}>Despesa</button></div><div className="grid grid-3" style={{marginTop:16}}><div className="field"><label>Data</label><input type="date" value={date} onChange={e=>setDate(e.target.value)} disabled={saving}/></div><div className="field"><label>Valor</label><input placeholder="0,00" value={amount} onChange={e=>setAmount(e.target.value)} disabled={saving}/></div>{type==='income'?<div className="field"><label>Plataforma</label><select value={platform} onChange={e=>setPlatform(e.target.value)} disabled={saving}><option>Uber</option><option>99</option><option>InDrive</option><option>Particular</option><option>Outro</option></select></div>:<div className="field"><label>Categoria</label><select value={category} onChange={e=>setCategory(e.target.value)} disabled={saving}><option>Combustível</option><option>Alimentação</option><option>Manutenção</option><option>Lavagem</option><option>Estacionamento</option><option>Pedágio</option><option>Seguro</option><option>Parcela do veículo</option><option>Outros</option></select></div>}</div><div className="field"><label>Descrição</label><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Opcional" disabled={saving}/></div><button className={`btn ${type==='income'?'btn-green':'btn-red'}`} onClick={save} disabled={saving}>{saving?'Salvando...':'Salvar lançamento'}</button></div>}
 <div className="grid grid-4" style={{marginTop:18}}><div className="card metric green"><div className="label">Faturamento</div><div className="value">{money(stats.income)}</div></div><div className="card metric red"><div className="label">Gastos</div><div className="value">{money(stats.expense)}</div></div><div className="card metric blue"><div className="label">Lucro</div><div className="value">{money(stats.profit)}</div></div><div className="card metric"><div className="label">Km rodados</div><div className="value">{km.toLocaleString('pt-BR')} km</div></div></div>
 <div className="grid grid-3" style={{marginTop:16}}><div className="card metric"><div className="label">Lucro por km</div><div className="value" style={{fontSize:22}}>{km?money(stats.profit/km):'R$ 0,00'}</div></div><div className="card metric"><div className="label">Horas trabalhadas</div><div className="value" style={{fontSize:22}}>{hours.toFixed(1)}h</div></div><div className="card metric"><div className="label">Lucro por hora</div><div className="value" style={{fontSize:22}}>{hours?money(stats.profit/hours):'R$ 0,00'}</div></div></div>
 <div className="card" style={{marginTop:16}}><h3>Faturamento x gastos x lucro</h3><div style={{height:320}}>{loading?<p>Carregando...</p>:<ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><XAxis dataKey="date"/><YAxis/><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend/><Bar dataKey="Faturamento" fill="#1565ff"/><Bar dataKey="Gastos" fill="#ef5350"/><Bar dataKey="Lucro" fill="#11a36a"/></BarChart></ResponsiveContainer>}</div></div></>
}
